[package]
name = "wsl2-ip-host-cli"
version = "1.5.0"
authors = ["fiburonsk <10441670+fiburonsk@users.noreply.github.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "wsl2-ip-host-cli"
path = "src/main.rs"

[dependencies]
main = { path = "../main" }

[build-dependencies]
winres = "0.1"
