[package]
name = "wsl2-ip-host-cli"
version = "1.4.1"
authors = ["fiburonsk <10441670+fiburonsk@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "wsl2-ip-host"
path = "src/main.rs"

[dependencies]
main = { path = "../main" }
