[package]
name = "wsl2-ip-host-win"
version = "0.1.0"
authors = ["fiburonsk <10441670+fiburonsk@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "wsl2-ip-host-gui"
path = "src/main.rs"

[dependencies]
main = { path = "../main" }
